[project]
name = "redis-pub-sub-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.11",
    "ty>=0.0.1a7",
]
